# Generated by Django 5.2.7 on 2026-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
