# Generated by Django 5.2.7 on 2026-08-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0004_destination_image_url_service_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='after_arrival_tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='airport_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='airport_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='before_arrival_tips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='currency_code',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='destination',
            name='hero_tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business Community'), ('local', 'Destination Local Business Community')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='journey_stage',
            field=models.CharField(choices=[('before_arrival', 'Before arrival'), ('after_arrival', 'After arrival'), ('both', 'Before and after arrival')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='location_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='priority_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
