# Generated by Django 5.2.7 on 2026-08-04 19:50

from django.db import migrations
from django.contrib.auth.hashers import make_password
from uuid import uuid4


DESTINATIONS = [
    {
        'code': 'NYC',
        'name': 'New York Destination Passport',
        'city': 'New York',
        'country': 'United States',
        'airport_code': 'JFK',
        'airport_name': 'John F. Kennedy International Airport',
        'currency_code': 'USD',
        'timezone': 'America/New_York',
        'hero_tagline': 'From touchdown to Times Square, everything starts with your ticket.',
        'description': 'Access airport conveniences, curated city experiences, dining, transport, and marketplace bookings in one New York destination passport.',
        'highlights': ['Broadway nights', 'Manhattan dining', 'Executive airport transfers', 'Premium arrival lounges'],
        'before_arrival_tips': ['Reserve your transfer before landing.', 'Book hotel and attraction slots in advance.', 'Keep your ticket ready as your destination pass.'],
        'after_arrival_tips': ['Head to the arrivals lounge for SIM, forex, and concierge support.', 'Unlock verified local rides and dining nearby.', 'Use the marketplace for last-minute bookings.'],
        'image_url': 'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 1,
    },
    {
        'code': 'LON',
        'name': 'London Destination Passport',
        'city': 'London',
        'country': 'United Kingdom',
        'airport_code': 'LHR',
        'airport_name': 'Heathrow Airport',
        'currency_code': 'GBP',
        'timezone': 'Europe/London',
        'hero_tagline': 'Arrive in London with instant access to airport and city essentials.',
        'description': 'Your London ticket unlocks airport lounges, fast transfers, hospitality, dining, and curated local experiences before and after arrival.',
        'highlights': ['West End experiences', 'Heathrow services', 'Luxury stays', 'City mobility passes'],
        'before_arrival_tips': ['Book Heathrow arrival support ahead of time.', 'Plan hotel and mobility passes before departure.', 'Save your ticket details for instant check-in access.'],
        'after_arrival_tips': ['Use airport concierge services immediately after arrival.', 'Activate your city transport and dining bookings.', 'Discover verified London experiences near your hotel.'],
        'image_url': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 2,
    },
    {
        'code': 'AMS',
        'name': 'Amsterdam Destination Passport',
        'city': 'Amsterdam',
        'country': 'Netherlands',
        'airport_code': 'AMS',
        'airport_name': 'Amsterdam Airport Schiphol',
        'currency_code': 'EUR',
        'timezone': 'Europe/Amsterdam',
        'hero_tagline': 'A seamless Schiphol-to-city experience tailored to your journey.',
        'description': 'Amsterdam combines airport services, local culture, accommodation, food, tours, and transport in one connected destination ecosystem.',
        'highlights': ['Canal-side stays', 'Schiphol lounges', 'Museum-ready itineraries', 'City welcome transfers'],
        'before_arrival_tips': ['Reserve Schiphol arrival and transport products early.', 'Pre-book museum and canal packages.', 'Review your destination passport for recommended businesses.'],
        'after_arrival_tips': ['Collect airport essentials before exiting arrivals.', 'Use verified transfers into the city center.', 'Book dining and tours from the same marketplace.'],
        'image_url': 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 3,
    },
    {
        'code': 'DXB',
        'name': 'Dubai Destination Passport',
        'city': 'Dubai',
        'country': 'United Arab Emirates',
        'airport_code': 'DXB',
        'airport_name': 'Dubai International Airport',
        'currency_code': 'AED',
        'timezone': 'Asia/Dubai',
        'hero_tagline': 'Touch down in Dubai with premium airport and city access built in.',
        'description': 'The Dubai destination passport blends airport retail, lounges, premium transport, hospitality, dining, and destination experiences into one platform.',
        'highlights': ['Premium arrivals', 'Desert excursions', 'Luxury shopping', 'Airport retail and dining'],
        'before_arrival_tips': ['Secure airport fast-track and chauffeur options early.', 'Pre-book desert, shopping, and wellness experiences.', 'Use your ticket as your digital marketplace key.'],
        'after_arrival_tips': ['Redeem airport lounge and transfer access on landing.', 'Browse verified hotels, dining, and attractions instantly.', 'Complete purchases from your destination passport.'],
        'image_url': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 4,
    },
    {
        'code': 'NBO',
        'name': 'Nairobi Destination Passport',
        'city': 'Nairobi',
        'country': 'Kenya',
        'airport_code': 'NBO',
        'airport_name': 'Jomo Kenyatta International Airport',
        'currency_code': 'KES',
        'timezone': 'Africa/Nairobi',
        'hero_tagline': 'From JKIA to the city, your Nairobi experience is already unlocked.',
        'description': 'The Nairobi passport connects airport hospitality, local transport, safari planning, accommodation, healthcare, and dining for Kenya Airways passengers.',
        'highlights': ['Safari planning', 'JKIA support', 'City dining', 'Trusted mobility and wellness'],
        'before_arrival_tips': ['Book airport pickup and safari add-ons before arrival.', 'Reserve restaurants and hotels from the same platform.', 'Check your personalized Nairobi recommendations before landing.'],
        'after_arrival_tips': ['Use airport lounges, transport, and forex on arrival.', 'Discover verified hotels, local food, and healthcare options.', 'Complete all destination bookings with one payment flow.'],
        'image_url': 'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 5,
    },
    {
        'code': 'CPT',
        'name': 'Cape Town Destination Passport',
        'city': 'Cape Town',
        'country': 'South Africa',
        'airport_code': 'CPT',
        'airport_name': 'Cape Town International Airport',
        'currency_code': 'ZAR',
        'timezone': 'Africa/Johannesburg',
        'hero_tagline': 'Your Cape Town ticket is your pass to airport comfort and coastal discovery.',
        'description': 'Cape Town demonstrates a localized business ecosystem with airport support, mobility, accommodation, culinary, wellness, and sightseeing services.',
        'highlights': ['Table Mountain access', 'Wine and dining', 'Airport-to-waterfront journeys', 'Wellness and recovery services'],
        'before_arrival_tips': ['Reserve transfers and attraction slots ahead of landing.', 'Lock in hotel and coastal experiences from your passport.', 'Review the airport and city communities before departure.'],
        'after_arrival_tips': ['Activate airport services as soon as you land.', 'Connect with verified local transport and dining.', 'Use the marketplace to complete same-day bookings.'],
        'image_url': 'https://images.unsplash.com/photo-1576485375217-d6a95e34d043?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 6,
    },
    {
        'code': 'BKK',
        'name': 'Bangkok Destination Passport',
        'city': 'Bangkok',
        'country': 'Thailand',
        'airport_code': 'BKK',
        'airport_name': 'Suvarnabhumi Airport',
        'currency_code': 'THB',
        'timezone': 'Asia/Bangkok',
        'hero_tagline': 'Land in Bangkok with a curated airport and city marketplace at your fingertips.',
        'description': 'Bangkok showcases a full destination passport: airport assistance, hospitality, transport, dining, tours, and wellness in one unified experience.',
        'highlights': ['Street food and culture', 'Airport hospitality', 'Riverfront stays', 'Temple and market tours'],
        'before_arrival_tips': ['Reserve arrival transfers and first-night essentials.', 'Pre-book dining, wellness, and tours.', 'Use your destination passport to compare trusted merchants.'],
        'after_arrival_tips': ['Start with airport dining, lounge, and transfer services.', 'Explore city stays, food, and tours right away.', 'Book and pay for local experiences in one checkout flow.'],
        'image_url': 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1200',
        'featured': True,
        'is_demo': True,
        'sort_order': 7,
    },
]

CATEGORIES = [
    ('Airport Lounge', '🛋️', 'Premium relaxation and business lounge access within the airport.'),
    ('Airport Transfer', '🚖', 'Airport transfers, chauffeurs, and arrival mobility services.'),
    ('Hotel', '🏨', 'Hotels and accommodation options near the destination.'),
    ('Restaurant', '🍽️', 'Dining, local cuisine, and culinary experiences.'),
    ('Tour', '🧭', 'Guided experiences, attractions, and cultural discovery.'),
    ('Transport', '🚌', 'City transport, passes, and local mobility providers.'),
    ('Healthcare', '🏥', 'Hospitals, pharmacies, wellness, and health support.'),
]


def _create_or_update_user(User, username, email, first_name, last_name, business_name, business_category):
    user = User.objects.filter(username=username).first()
    if user is None:
        user = User(
            id=uuid4().hex,
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            user_type='business_partner',
            password=make_password(None),
        )
    user.business_name = business_name
    user.business_verified = True
    user.business_category = business_category
    user.save()
    return user


def create_demo_destination_passports(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Destination = apps.get_model('trip_assistant', 'Destination')
    ServiceCategory = apps.get_model('trip_assistant', 'ServiceCategory')
    Service = apps.get_model('trip_assistant', 'Service')

    category_map = {}
    for name, icon, description in CATEGORIES:
        category = ServiceCategory.objects.filter(name=name).first()
        if category is None:
            category = ServiceCategory.objects.create(
                id=uuid4().hex,
                name=name,
                icon=icon,
                description=description,
            )
        else:
            category.icon = icon
            category.description = description
            category.save(update_fields=['icon', 'description'])
        category_map[name] = category

    for destination_data in DESTINATIONS:
        destination = Destination.objects.filter(code=destination_data['code']).first()
        if destination is None:
            destination = Destination.objects.create(
                id=uuid4().hex,
                **destination_data,
            )
        else:
            for key, value in destination_data.items():
                setattr(destination, key, value)
            destination.save()

        airport_user = _create_or_update_user(
            User,
            username=f"{destination.code.lower()}_airport_partner",
            email=f"{destination.code.lower()}-airport@vibekq.demo",
            first_name=destination.city,
            last_name='Airport',
            business_name=f"{destination.city} Airport Services Hub",
            business_category='Airport Services',
        )
        local_user = _create_or_update_user(
            User,
            username=f"{destination.code.lower()}_local_partner",
            email=f"{destination.code.lower()}-local@vibekq.demo",
            first_name=destination.city,
            last_name='Local',
            business_name=f"{destination.city} Welcome Collective",
            business_category='Destination Experiences',
        )

        services = [
            {
                'name': f"{destination.airport_code} Gateway Lounge Access",
                'category': category_map['Airport Lounge'],
                'provider': airport_user,
                'description': f"Relax, refresh, and get concierge support inside {destination.airport_name} before departure or immediately after landing.",
                'community_type': 'airport',
                'journey_stage': 'both',
                'location_label': f"{destination.airport_name} Terminal Experience Zone",
                'tags': ['premium', 'business', 'comfort', 'relaxation'],
                'priority_score': 95,
                'price': '45.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.8',
                'total_bookings': 120,
                'available': True,
            },
            {
                'name': f"{destination.city} Express Arrival Transfer",
                'category': category_map['Airport Transfer'],
                'provider': airport_user,
                'description': f"Pre-booked arrival pickup from {destination.airport_code} with luggage assistance and direct transfer into {destination.city}.",
                'community_type': 'airport',
                'journey_stage': 'after_arrival',
                'location_label': f"{destination.airport_name} Arrivals",
                'tags': ['transport', 'arrival', 'family', 'business'],
                'priority_score': 92,
                'price': '32.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.7',
                'total_bookings': 180,
                'available': True,
            },
            {
                'name': f"{destination.city} Signature Stay Collection",
                'category': category_map['Hotel'],
                'provider': local_user,
                'description': f"Destination-ready accommodation options curated for Kenya Airways passengers in prime {destination.city} neighborhoods.",
                'community_type': 'local',
                'journey_stage': 'before_arrival',
                'location_label': f"Central {destination.city}",
                'tags': ['accommodation', 'luxury', 'business', 'family'],
                'priority_score': 88,
                'price': '140.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.9',
                'total_bookings': 75,
                'available': True,
            },
            {
                'name': f"{destination.city} Food & Culture Trail",
                'category': category_map['Restaurant'],
                'provider': local_user,
                'description': f"Reserve a dining and neighborhood tasting experience that introduces passengers to the flavor of {destination.city}.",
                'community_type': 'local',
                'journey_stage': 'both',
                'location_label': f"{destination.city} Dining District",
                'tags': ['food', 'culture', 'family', 'local'],
                'priority_score': 84,
                'price': '55.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.8',
                'total_bookings': 140,
                'available': True,
            },
            {
                'name': f"{destination.city} Highlights Discovery Tour",
                'category': category_map['Tour'],
                'provider': local_user,
                'description': f"A verified introduction to the must-see attractions, business districts, and hidden gems across {destination.city}.",
                'community_type': 'local',
                'journey_stage': 'before_arrival',
                'location_label': f"{destination.city} City Center",
                'tags': ['adventure', 'culture', 'sightseeing', 'premium'],
                'priority_score': 86,
                'price': '68.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.7',
                'total_bookings': 98,
                'available': True,
            },
            {
                'name': f"{destination.city} Welcome Mobility Pass",
                'category': category_map['Transport'],
                'provider': local_user,
                'description': f"Instant access to trusted local mobility providers, city rides, and transfers across {destination.city}.",
                'community_type': 'local',
                'journey_stage': 'after_arrival',
                'location_label': f"{destination.city} Metro Area",
                'tags': ['transport', 'convenience', 'family', 'budget'],
                'priority_score': 82,
                'price': '24.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.6',
                'total_bookings': 155,
                'available': True,
            },
            {
                'name': f"{destination.city} Care & Wellness Access",
                'category': category_map['Healthcare'],
                'provider': local_user,
                'description': f"Connect with trusted pharmacies, clinics, and wellness providers in {destination.city} as soon as you land.",
                'community_type': 'local',
                'journey_stage': 'after_arrival',
                'location_label': f"{destination.city} Health Network",
                'tags': ['healthcare', 'wellness', 'family', 'support'],
                'priority_score': 78,
                'price': '20.00',
                'currency': destination.currency_code,
                'image_url': destination.image_url,
                'verified': True,
                'rating': '4.5',
                'total_bookings': 60,
                'available': True,
            },
        ]

        for service_data in services:
            service = Service.objects.filter(destination=destination, name=service_data['name']).first()
            if service is None:
                Service.objects.create(
                    id=uuid4().hex,
                    destination=destination,
                    **service_data,
                )
            else:
                for key, value in service_data.items():
                    setattr(service, key, value)
                service.destination = destination
                service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passengerprofile_ticketverification_linked_destination'),
        ('trip_assistant', '0005_destination_passport_fields'),
    ]

    operations = [
        migrations.RunPython(create_demo_destination_passports, migrations.RunPython.noop),
    ]
