# Generated by Django 5.2.7 on 2026-08-05 22:00

from django.db import migrations, models


def migrate_destination_business_values(apps, schema_editor):
    Service = apps.get_model('trip_assistant', 'Service')
    Service.objects.filter(community_type='local').update(community_type='destination')


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0006_seed_demo_destination_passports'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='business_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='service',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business'), ('destination', 'Destination Business')], default='destination', max_length=20),
        ),
        migrations.RunPython(migrate_destination_business_values, migrations.RunPython.noop),
    ]
