# Generated by Django 5.2.7 on 2026-09-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0005_destination_welcome_messages'),
        ('trip_assistant', '0008_destination_welcome_experience_copy'),
    ]

    operations = [
    ]
