# Generated by Django 5.2.7 on 2026-09-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0009_merge_20260910_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['sort_order', '-featured', 'name']},
        ),
    ]
