# Generated by Django 5.2.7 on 2025-10-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_community', '0002_eventparticipant_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeMemory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='vibe_memories/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vibe Memories',
                'ordering': ['-created_at'],
            },
        ),
    ]
