# Generated by Django 5.2.7 on 2026-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_community', '0003_vibememory'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vibememory',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL fallback', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchandise/'),
        ),
        migrations.AlterField(
            model_name='vibememory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vibe_memories/'),
        ),
    ]
