# Generated by Django 5.2.7 on 2026-08-04 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0005_destination_passport_fields'),
        ('business_community', '0002_alter_partnerapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business Community'), ('local', 'Destination Local Business Community')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_applications', to='trip_assistant.destination'),
        ),
        migrations.AddField(
            model_name='partnerapplication',
            name='service_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partnership',
            name='community_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnership',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business Community'), ('local', 'Destination Local Business Community')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='partnership',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships', to='trip_assistant.destination'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnership',
            name='service_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sponsoredcontent',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business Community'), ('local', 'Destination Local Business Community')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsoredcontent',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_content', to='trip_assistant.destination'),
        ),
    ]
