# Generated by Django 5.2.7 on 2026-08-04 19:55

from django.db import migrations
from uuid import uuid4


def seed_demo_partnerships(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Destination = apps.get_model('trip_assistant', 'Destination')
    Partnership = apps.get_model('business_community', 'Partnership')

    for destination in Destination.objects.filter(is_demo=True):
        partner_specs = [
            {
                'username': f"{destination.code.lower()}_airport_partner",
                'community_type': 'airport',
                'business_category': 'Airport Services',
                'summary': f"Curated airport lounges, arrival assistance, transfers, and services for passengers using {destination.airport_code}.",
                'tags': ['airport', 'arrival', 'lounge', 'transport'],
                'featured': True,
            },
            {
                'username': f"{destination.code.lower()}_local_partner",
                'community_type': 'local',
                'business_category': 'Destination Experiences',
                'summary': f"Verified city services across accommodation, dining, attractions, transport, and wellness in {destination.city}.",
                'tags': ['hotel', 'restaurant', 'tour', 'transport', 'wellness'],
                'featured': True,
            },
        ]

        for spec in partner_specs:
            user = User.objects.filter(username=spec['username']).first()
            if user is None:
                continue

            partnership = Partnership.objects.filter(user=user).first()
            if partnership is None:
                partnership = Partnership(id=uuid4().hex, user=user)

            partnership.business_name = user.business_name or user.username
            partnership.business_category = spec['business_category']
            partnership.destination = destination
            partnership.community_type = spec['community_type']
            partnership.service_tags = spec['tags']
            partnership.community_summary = spec['summary']
            partnership.featured = spec['featured']
            partnership.commission_rate = '10.00'
            partnership.total_revenue = '0.00'
            partnership.total_bookings = 0
            partnership.rating = '4.80' if spec['community_type'] == 'airport' else '4.90'
            partnership.active = True
            partnership.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0006_seed_demo_destination_passports'),
        ('business_community', '0003_destination_community_fields'),
    ]

    operations = [
        migrations.RunPython(seed_demo_partnerships, migrations.RunPython.noop),
    ]
