# Generated by Django 5.2.7 on 2026-08-05 22:05

from django.db import migrations, models


def migrate_destination_business_values(apps, schema_editor):
    PartnerApplication = apps.get_model('business_community', 'PartnerApplication')
    Partnership = apps.get_model('business_community', 'Partnership')
    SponsoredContent = apps.get_model('business_community', 'SponsoredContent')

    PartnerApplication.objects.filter(community_type='local').update(community_type='destination')
    Partnership.objects.filter(community_type='local').update(community_type='destination')
    SponsoredContent.objects.filter(community_type='local').update(community_type='destination')


class Migration(migrations.Migration):

    dependencies = [
        ('business_community', '0004_seed_demo_partnerships'),
        ('trip_assistant', '0007_destination_business_and_payment_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerapplication',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business'), ('destination', 'Destination Business')], default='destination', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business'), ('destination', 'Destination Business')], default='destination', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsoredcontent',
            name='community_type',
            field=models.CharField(choices=[('airport', 'Airport Business'), ('destination', 'Destination Business')], default='destination', max_length=20),
        ),
        migrations.RunPython(migrate_destination_business_values, migrations.RunPython.noop),
    ]
