# Generated by Django 5.2.7 on 2025-10-26 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TicketVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(max_length=50)),
                ('passenger_name', models.CharField(max_length=255)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_response', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Verification',
                'verbose_name_plural': 'Ticket Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
