# Generated by Django 5.2.7 on 2026-08-04 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_assistant', '0004_destination_image_url_service_image_url_and_more'),
        ('accounts', '0003_user_last_ticket_number_user_passport_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('travel_styles', models.JSONField(blank=True, default=list)),
                ('preferred_airport_services', models.JSONField(blank=True, default=list)),
                ('preferred_local_experiences', models.JSONField(blank=True, default=list)),
                ('preferred_transport_modes', models.JSONField(blank=True, default=list)),
                ('favorite_destinations', models.JSONField(blank=True, default=list)),
                ('preferred_budget', models.CharField(choices=[('budget', 'Budget'), ('mid_range', 'Mid-range'), ('premium', 'Premium'), ('luxury', 'Luxury')], default='mid_range', max_length=20)),
                ('travel_frequency', models.CharField(choices=[('first_time', 'First-time traveler'), ('occasional', 'Occasional traveler'), ('frequent', 'Frequent traveler'), ('road_warrior', 'Road warrior')], default='occasional', max_length=20)),
                ('dietary_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('accessibility_needs', models.TextField(blank=True, null=True)),
                ('recommendation_notes', models.TextField(blank=True, null=True)),
                ('last_landed_at', models.DateTimeField(blank=True, null=True)),
                ('current_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_passenger_profiles', to='trip_assistant.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='ticketverification',
            name='linked_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_verifications', to='trip_assistant.destination'),
        ),
    ]
